import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  const page1Promise = page.waitForEvent('popup');
  await page.goto('https://efgp.yuchens.com:8086/NaNaWeb/');
  const page1 = await page1Promise;
  await page1.getByRole('textbox', { name: 'LDAP 代 號' }).fill('boyawu');
  await page1.getByRole('textbox', { name: 'LDAP 代 號' }).press('Tab');
  await page1.getByRole('textbox', { name: '密 碼' }).fill('qwertyuiop[]');
  await page1.getByRole('button', { name: '登入' }).click();
  await page.goto('http://efgp.yuchens.com/SYSSetting/PMSetting.aspx?empid=10101209');
  await page.locator('#txtProject').click();
  await page.locator('#txtProject').fill('PY265-0080');
  await page.getByRole('button', { name: '查詢' }).click();
  await page.getByRole('cell', { name: '無相關資料' }).click();
  await page.locator('#txtPMEmp').click();
  await page.locator('#txtPMEmp').fill('10101209');
  await page.getByRole('button', { name: '新增' }).click();
  await page.locator('#txtProject').click();
  await page.locator('#txtProject').fill('PY265-0080');
  await page.getByRole('button', { name: '查詢' }).click();
  await page.getByRole('button', { name: 'WorkItem' }).click();
  await page.locator('#txtNum').click();
  await page.locator('#txtNum').fill('1');
  await page.locator('#txtWorkItem').click();
  await page.locator('#txtWorkItem').fill('\t專案庶務及聯繫');
  await page.locator('#txtWorkItem').click();
  await page.locator('#txtWorkItem').fill('專案庶務及聯繫');
  await page.locator('#txtHour').click();
  await page.locator('#txtHour').fill('100');
  await page.locator('#txtAlarmHour').click();
  await page.locator('#txtAlarmHour').fill('100');
  await page.getByRole('button', { name: '新 增' }).click();
  await page.locator('#txtNum').click();
  await page.locator('#txtNum').fill('2');
  await page.locator('#txtWorkItem').click();
  await page.locator('#txtWorkItem').fill('軟體建置開發及測試');
  await page.locator('#txtHour').click();
  await page.locator('#txtHour').fill('100');
  await page.locator('#txtAlarmHour').click();
  await page.locator('#txtAlarmHour').fill('100');
  await page.getByRole('button', { name: '新 增' }).click();
  await page.locator('#txtNum').click();
  await page.locator('#txtNum').fill('3');
  await page.locator('#txtWorkItem').click();
  await page.locator('#txtWorkItem').fill('硬體施工、廠勘釐清');
  await page.locator('#txtHour').click();
  await page.locator('#txtHour').fill('24');
  await page.locator('#txtAlarmHour').click();
  await page.locator('#txtAlarmHour').fill('16');
  await page.getByRole('button', { name: '新 增' }).click();
  await page.locator('#txtNum').click();
  await page.locator('#txtNum').fill('4');
  await page.locator('#txtWorkItem').click();
  await page.locator('#txtWorkItem').click();
  await page.locator('#txtWorkItem').fill('專案請款、業主聯繫追蹤');
  await page.locator('#txtHour').click();
  await page.locator('#txtHour').fill('160');
  await page.locator('#txtHour').press('Tab');
  await page.locator('#txtAlarmHour').fill('100');
  await page.getByRole('button', { name: '新 增' }).click();
  await page.locator('#txtNum').click();
  await page.locator('#txtNum').fill('5');
  await page.locator('#txtWorkItem').click();
  await page.locator('#txtWorkItem').fill('料件選型、詢價及請購相關');
  await page.locator('#txtHour').click();
  await page.locator('#txtHour').fill('111');
  await page.locator('#txtAlarmHour').click();
  await page.locator('#txtAlarmHour').fill('111');
  await page.getByRole('button', { name: '新 增' }).click();
});